CDISC Vocabulary introduction
OHDSI/Vocabulary-v5.0 pull request #1036
Opened 2024-08-01 13:24 UTC by IrynaZherka

2024-08-01 13:54 UTC, TinyRickC137 requested changes
ICD commits in CDISC pull request

2024-08-01 14:09 UTC, TinyRickC137 approved these changes

2024-08-01 15:06 UTC, TinyRickC137 requested changes
as discussed in skype

2024-08-02 08:29 UTC, TinyRickC137 commented on CDISC/manual_work/create_source_tables.sql
> +--Create source table to be filled during 'load_stage' before stage tables created
Drop file

2024-08-02 15:30 UTC, TinyRickC137 commented on CDISC/load_stage.sql
> +FROM dev_cdisc.source s
why is there dev_cdisk?

2024-08-05 14:56 UTC, TinyRickC137 approved these changes

2024-08-12 10:49 UTC, AlaikseiKatyshou approved these changes

2024-08-12 10:50 UTC, vladkorsik commented on CDISC/load_stage.sql
> +FROM dev_cdisc.source s
was preserved for one LK only

2024-08-12 10:54 UTC, merged