Add processing for manual tables in ICD10PCS load stage
OHDSI/Vocabulary-v5.0 pull request #405
Opened 2020-10-23 12:16 UTC by ekorchmar

2020-10-23 12:43 UTC, hardhouse requested changes
1. if you move ProcessManualRelationships down, then p.11 may lose your changes
2. CheckManualConcepts and ProcessManualRelationships cannot be lower in the list than the CheckReplacementMappings, AddFreshMAPSTO etc for same reason
3. please don't change the case of letters of these procedures

2020-10-26 16:55 UTC, dimshitc approved these changes

2020-10-26 17:23 UTC, hardhouse commented
1. remove "least"
2. re-order manual procedures: 11, then 9, then 10

2020-10-28 13:27 UTC, hardhouse approved these changes

2020-10-28 13:27 UTC, merged