NCCD GitHub release
OHDSI/Vocabulary-v5.0 pull request #420
Opened 2020-11-20 10:39 UTC by divakhnenko

2020-11-20 11:30 UTC, hardhouse requested changes
1. missing standard block with * _stage tables truncation in load_stage.sql (e.g. concept_synonym_stage will contain duplicates)
2. why do we need all the index drops (https://github.com/OHDSI/Vocabulary-v5.0/blob/521e1e58e0c9ef84eeefb25663a1386a0d202da4/NCCD/load_stage.sql#L119) if we are already dropping the entire table above?
3. unnecessary casting https://github.com/OHDSI/Vocabulary-v5.0/blob/521e1e58e0c9ef84eeefb25663a1386a0d202da4/NCCD/load_stage.sql#L385 (t1.numerator_value already has NUMERIC type).
4. https://github.com/OHDSI/Vocabulary-v5.0/blob/521e1e58e0c9ef84eeefb25663a1386a0d202da4/NCCD/load_stage.sql#L443 strange code
5. dont use double (!) DISCTINCT with UNION https://github.com/OHDSI/Vocabulary-v5.0/blob/521e1e58e0c9ef84eeefb25663a1386a0d202da4/NCCD/load_stage.sql#L559 and https://github.com/OHDSI/Vocabulary-v5.0/blob/521e1e58e0c9ef84eeefb25663a1386a0d202da4/NCCD/load_stage.sql#L567
6. distinct+union for unique strings? https://github.com/OHDSI/Vocabulary-v5.0/blob/521e1e58e0c9ef84eeefb25663a1386a0d202da4/NCCD/load_stage.sql#L644
7. remove all prefixes "devv5."
8. unnecessary unions again https://github.com/OHDSI/Vocabulary-v5.0/blob/521e1e58e0c9ef84eeefb25663a1386a0d202da4/NCCD/load_stage.sql#L679
9. https://github.com/OHDSI/Vocabulary-v5.0/blob/521e1e58e0c9ef84eeefb25663a1386a0d202da4/NCCD/load_stage.sql#L780 why are these alter's?
10. https://github.com/OHDSI/Vocabulary-v5.0/blob/521e1e58e0c9ef84eeefb25663a1386a0d202da4/NCCD/load_stage.sql#L790 vocabulary already exists

2020-11-20 19:40 UTC, dimshitc commented
к первому пункту - скрипт не Load_Stage должен называться, а create_input_tables.sql - то, что скормят бойлеру. а там уже есть 
https://github.com/OHDSI/Vocabulary-v5.0/blob/master/working/Build_RxE.sql#L5065 эти truncate
вот и у Эдика в dm+d https://github.com/OHDSI/Vocabulary-v5.0/blob/master/dmd/load_stage.sql такой же скрипт называется load_Stage, я думаю - это неправильно.
и кстати, действительно можно написать load_stage, если сделать из бойлера функцию. 
тогда я могу написать все  свои превращения для create input, а потом вызвать бойлер там же

2020-11-20 19:46 UTC, hardhouse commented
> а там уже есть
> https://github.com/OHDSI/Vocabulary-v5.0/blob/master/working/Build_RxE.sql#L5065 эти truncate

есть, но не все. для синонимов нет (потому что бойлер туда и не пишет). поэтому повторный вызов скриптов без фаста будет давать дубли в синонимах
в любом случае, если есть/будет load_stage, стандартные транкейты обязательно должны быть во избежания недоразумений (может там будут данные от других скриптов, мало ли кто и что гонял в схеме)
ну и плюс есть мысль убрать транкейты в будущем из бойлера - это не его дело
так что предлагаю изначально писать правильный код

2020-11-23 13:10 UTC, dimshitc commented
Тимур, а что думаешь на счет названий скриптов / встраивания бойлера как
функции?

On Fri, Nov 20, 2020 at 9:47 PM Timur <notifications@github.com> wrote:

> а там уже есть
>
> https://github.com/OHDSI/Vocabulary-v5.0/blob/master/working/Build_RxE.sql#L5065
> эти truncate
>
> есть, но не все. для синонимов нет (потому что бойлер туда и не пишет).
> поэтому повторный вызов скриптов без фаста будет давать дубли в синонимах
> в любом случае, если есть/будет load_stage, стандартные транкейты
> обязательно должны быть во избежания недоразумений (может там будут данные
> от других скриптов, мало ли кто и что гонял в схеме)
> ну и плюс есть мысль убрать транкейты в будущем из бойлера - это не его
> дело
> так что предлагаю изначально писать правильный код
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/OHDSI/Vocabulary-v5.0/pull/420#issuecomment-731373142>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACBMA726OZ4Y4BU6SNSX3V3SQ3BTPANCNFSM4T4TJX4Q>
> .
>

2020-11-23 13:27 UTC, hardhouse commented
названия хорошие, про функцию я был бы рад, но что-то есть большие сомнения в том, насколько остальным будет удобно дебажить код в будущем и делать PR

2020-11-23 14:24 UTC, divakhnenko commented
> 4\. https://github.com/OHDSI/Vocabulary-v5.0/blob/521e1e58e0c9ef84eeefb25663a1386a0d202da4/NCCD/load_stage.sql#L443
>      strange code

Эта часть чистит дозировки и избавляется от лишних нулей. Я попробую без нее прогнать, но мне кажется, что создадутся новыу ненужные концепты из-за оставшихся нулей

2020-11-23 14:26 UTC, Alexdavv commented
> я думаю - это неправильно

Не менее неправельным выглядит то, что нам бойлер [запрещает заполнять стэйджи заранее](https://github.com/OHDSI/Vocabulary-v5.0/blob/ef749c96b32b09e87b21350839c91024d36ff8ef/working/Build_RxE.sql#L5065).
Но мы все равно это [делаем](https://github.com/OHDSI/Vocabulary-v5.0/blob/ef749c96b32b09e87b21350839c91024d36ff8ef/Gemscript/load_stage.sql#L73).
В итого [имеем то, что имеем](https://github.com/OHDSI/Vocabulary-v5.0/blob/ef749c96b32b09e87b21350839c91024d36ff8ef/Gemscript/load_stage.sql#L3216).

По-моему именно отсюда растут ноги отсутствия конвенции по именованию этих скриптов.


> есть мысль убрать транкейты в будущем из бойлера - это не его дело.

Отлично. Транкейты все равно будут в load_stage.
Положим это в соседий PR, где как раз прявят бойлер?

2020-11-23 14:50 UTC, hardhouse commented
> избавляется от лишних нулей

the problem is that you shouldn't have extra zeros
+ i found more bugs
https://github.com/OHDSI/Vocabulary-v5.0/blob/c56951ea1c2a8982b68544d848998691ec50ac12/NCCD/load_stage.sql#L243
https://github.com/OHDSI/Vocabulary-v5.0/blob/c56951ea1c2a8982b68544d848998691ec50ac12/NCCD/load_stage.sql#L296
https://github.com/OHDSI/Vocabulary-v5.0/blob/c56951ea1c2a8982b68544d848998691ec50ac12/NCCD/load_stage.sql#L342
https://github.com/OHDSI/Vocabulary-v5.0/blob/c56951ea1c2a8982b68544d848998691ec50ac12/NCCD/load_stage.sql#L396
why float if we have denominator_value=numeric?
https://github.com/OHDSI/Vocabulary-v5.0/blob/c56951ea1c2a8982b68544d848998691ec50ac12/NCCD/load_stage.sql#L59

perhaps due to the use of float (here and / or somewhere else) you have these errors. never use float, only numeric type, see example:

select  '3.6000000000000009'::numeric::text
union all
select  '3.6000000000000009'::float::text

float is an imprecise type, it can lead to unexpected roundings and imprecise calculations

2020-11-24 10:53 UTC, divakhnenko commented
> the problem is that you shouldn't have extra zeros

Another reason for having additional zeros is multiplication and division of the numeric numerator_values. It is possible to get rid of them using casting _::double precision_. Can we do this?

2020-11-24 11:15 UTC, divakhnenko commented
> It is possible to get rid of them using casting _::double precision_. Can we do this?

It was a bad idea. New concepts will be unnecessarily created due to the fact that _::double precision_ makes rounding where it shouldn't be done

2020-11-24 14:05 UTC, hardhouse approved these changes
discussed on skype

2020-12-01 16:26 UTC, dimshitc approved these changes

2020-12-02 15:05 UTC, merged