Fixed replaced VMPs not getting new mappings
OHDSI/Vocabulary-v5.0 pull request #457
Opened 2021-02-11 14:46 UTC by ekorchmar

2021-02-11 16:01 UTC, dimshitc commented on dmd/postprocessing.sql
> +select devv5.genericupdate()
Why is it here???

2021-02-11 16:01 UTC, dimshitc requested changes
As usual:
Put manual tables to Google drive, put the link to the readme
+ remove generic_update

2021-02-11 16:33 UTC, ekorchmar commented on dmd/postprocessing.sql
> +select devv5.genericupdate()
it's how it was on my PC. fixing now

2023-02-01 12:44 UTC, Alexdavv commented
@TinyRickC137 Do we consider this in the current dmd development?

2023-02-02 08:51 UTC, TinyRickC137 commented
@Alexdavv yes, I took all the available branches

2024-02-20 08:56 UTC, closed without merging