maintenance update, we still need a big refactoring
OHDSI/Vocabulary-v5.0 pull request #462
Opened 2021-02-19 13:03 UTC by ekorchmar

2021-02-19 13:06 UTC, hardhouse approved these changes

2021-02-19 14:51 UTC, dimshitc requested changes
Please, please put all manual tables on the google drive and put the link in the README

2021-02-20 12:56 UTC, dimshitc commented on ICD10PCS/snomed_hierarchy/rxnorm_map_snippet.sql
> +{\rtf1\ansi\ansicpg1252\cocoartf2576
WTF?

2021-02-23 12:43 UTC, dimshitc approved these changes

2021-02-24 16:55 UTC, dimshitc approved these changes

2021-02-25 15:07 UTC, dimshitc approved these changes

2021-02-25 15:09 UTC, merged