Icd10 documentation
OHDSI/Vocabulary-v5.0 pull request #473
Opened 2021-03-16 11:13 UTC by divakhnenko

New documentation for uploading and updating ICD10 was created. However, it seems that links in readme.md have to be changed after PR (now they lead to icd10-documentation branch)

2021-03-16 11:17 UTC, hardhouse approved these changes

2021-03-29 20:21 UTC, Alexdavv requested changes
Just in case: https://github.com/OHDSI/Vocabulary-v5.0/pull/473#commitcomment-48746296

2021-03-30 12:21 UTC, divakhnenko commented
> Do we really want to have the scripts inside the documentation? Wouldn’t it be better to have a well-annotated refresh script?

Good idea! I hid scripts in files. And slightly changed readme (separate manual work - now you can find it in manual_work/readme.md)

2021-04-08 13:02 UTC, dimshitc approved these changes

2021-04-12 13:56 UTC, Alexdavv approved these changes

2021-04-12 13:59 UTC, merged