Hcpcs refresh 2022
OHDSI/Vocabulary-v5.0 pull request #676
Opened 2022-09-08 08:14 UTC by m-khitrun

2022-10-31 18:56 UTC, Alexdavv approved these changes
Urgent release for #697
Script to be refactored looking further

2022-10-31 19:31 UTC, hardhouse requested changes
leaved for subsequent period

```sql
UPDATE concept_stage cs
SET domain_id = i.domain_id
FROM (
	SELECT DISTINCT ON (crs.concept_code_1) crs.concept_code_1,
		c.domain_id
	FROM concept_relationship_stage crs
	JOIN concept c ON c.concept_code = crs.concept_code_2
		AND c.vocabulary_id = crs.vocabulary_id_2
	WHERE crs.relationship_id = 'Maps to'
		AND crs.invalid_reason IS NULL
		AND crs.vocabulary_id_1 = 'HCPCS'
	ORDER BY crs.concept_code_1,
		CASE c.domain_id
			WHEN 'Drug'
				THEN 1
			WHEN 'Visit'
				THEN 2
			WHEN 'Provider'
				THEN 3
			WHEN 'Device'
				THEN 4
			END
	) i
WHERE cs.concept_code = i.concept_code_1;
```

2023-02-22 09:21 UTC, TinyRickC137 approved these changes

2023-02-22 13:26 UTC, hardhouse approved these changes

2023-02-22 13:27 UTC, merged

2023-03-31 09:13 UTC, m-khitrun commented on HCPCS/load_stage.sql
> +					AND c.valid_end_date < TO_DATE('20991231', 'YYYYMMDD')
Documentation fixed

2023-04-03 11:40 UTC, m-khitrun commented on HCPCS/readme.md
Deleted