Ci vi c
OHDSI/Vocabulary-v5.0 pull request #688
Opened 2022-10-05 13:46 UTC by varvarenius

CIViC load stage for checks and merge

2022-10-06 15:38 UTC, Alexdavv commented on CIViC/load_stage.sql
> +    	and c.vocabulary_id = 'CIViC'
Why do we look back to the existing CIVIC concepts?

2022-10-06 15:53 UTC, Alexdavv requested changes
In general, a temporary civic_source table is not a working solution looking forward:
- it's not a source, it's something processed;
- it doesn't help in any way, because the INSERTS into the stage tables don't add any substantial logic, but become too weird and too deep embedded.
@hardhouse What do you think?

2022-10-06 15:53 UTC, Alexdavv commented on CIViC/load_stage.sql
> +	pVocabularyVersion		=> 'CIViC'||TO_CHAR(CURRENT_DATE,'YYYYMMDD'),
Why is it a current date? Don't we have a date/version coming from the source?

2022-10-06 15:53 UTC, Alexdavv commented on CIViC/load_stage.sql
> +       COALESCE(c.concept_id, NULL::int)  as concept_id,
We never populate the concept_id field in the stage tables. Generic_update function does it

2022-10-07 10:26 UTC, hardhouse requested changes

2022-10-07 10:26 UTC, hardhouse commented on CIViC/load_stage.sql
> +with s as (SELECT DISTINCT
distinct is not needed here

2022-10-07 10:26 UTC, hardhouse commented on CIViC/load_stage.sql
> +       trim(substr(n.concept_name,1,255)) AS concept_name,
don't do that, use vocabulary_pack.CutConceptName() (see our "SQL technical guide, common problems and tricks", p.1)

2022-10-07 10:26 UTC, hardhouse commented on CIViC/load_stage.sql
> +      COALESCE(c.valid_start_date, v.latest_update)   as valid_start_date, -- defines valid_start_date  based on previous vocabulary run
if valid_start_date=latest_update, the generic [will leave the old date](https://github.com/OHDSI/Vocabulary-v5.0/blob/master/working/generic_update.sql#L121)

2022-10-07 10:26 UTC, hardhouse commented on CIViC/load_stage.sql
> +       COALESCE(c.valid_end_date,TO_DATE('20991231', 'yyyymmdd'))  as valid_end_date -- defines valid_end_date  based on previous vocabulary run
if the concept is alive in the source, but D or U in the concept, then why should it remain deprecated?
why do we need the concept table here at all?

2022-10-07 10:26 UTC, hardhouse commented on CIViC/load_stage.sql
> +SELECT distinct
looks like a useless query

2022-10-07 10:26 UTC, hardhouse commented on CIViC/load_stage.sql
> +DISTINCT NULL::INT as synonym_concept_id,
is a distinct necessary here?

2022-10-07 10:26 UTC, hardhouse commented on CIViC/load_stage.sql
> +where synonym_name is not null
how can this field be null?

2022-10-07 10:26 UTC, hardhouse commented
1. please, resolve conflicts (CIViC/create_source_tables.sql already exists in master). so just remove yours from this PR
2. add a number to each item with comments
3. add all missing truncate of stage tables
4. why do you write "cast(variant_id as varchar(5))", because i asked in advance, whether this field should be made int or not?
5. why do you use distinct+union? please read our "SQL technical guide, common problems and tricks", p.6
6. do not abuse regular expressions, for example, instead of "variant!~*'rs'" you need to write "variant not ilike '%rs%'", it works faster. same for "::"
7. add clean-up (drop civic_source)
8. add the last line with standard text "-- At the end, the three tables concept_stage..."

2022-10-07 14:58 UTC, varvarenius commented
@hardhouse why do you write "cast(variant_id as varchar(5))", because i asked in advance, whether this field should be made int or not? - 
Type of source data is int, but we use this field as concept_code, which should be varchar. Is it worth to pull the source again with another type of this field or not?

2022-10-14 11:13 UTC, hardhouse approved these changes

2022-10-27 10:54 UTC, Alexdavv approved these changes

2022-10-27 11:14 UTC, merged