Omop Extension automatic assign of domain and class
OHDSI/Vocabulary-v5.0 pull request #693
Opened 2022-10-12 12:34 UTC by MariaRohozhkina

2022-10-24 19:06 UTC, Alexdavv requested changes
- There's an unexpected Domain switch for 50+ concepts (see the checks).
- 384/1k concepts require hardcoding of Domain. Does the logic work in general?
- Please revert the changes and let's make an urgent release

2023-01-10 10:27 UTC, hardhouse approved these changes

2023-01-10 12:18 UTC, Alexdavv approved these changes

2023-01-10 12:19 UTC, merged

2023-01-10 12:20 UTC, Alexdavv commented
@MariaRohozhkina Let's document 2 lists to be worked with:
- the list of SNOMED concepts to fix the Domains;
- list of OMOP Extension concepts to remove the details from the manual table once SNOMED Domains are fixed.